-- MySQL Script generated by MySQL Workbench
-- Fri Jun  7 22:28:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema quizshow_millionaire
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quizshow_millionaire
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quizshow_millionaire` DEFAULT CHARACTER SET utf8 ;
USE `quizshow_millionaire` ;

-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`Permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`Permission` (
  `idPermission` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idPermission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`Permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`Permissions` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `idPermission` INT NOT NULL,
  `RoleName` VARCHAR(45) NULL,
  PRIMARY KEY (`idRoles`),
  UNIQUE INDEX `idRoles_UNIQUE` (`idRoles` ASC),
  INDEX `fk_Permissions_Permission1_idx` (`idPermission` ASC),
  CONSTRAINT `fk_Permissions_Permission1`
    FOREIGN KEY (`idPermission`)
    REFERENCES `quizshow_millionaire`.`Permission` (`idPermission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `idRoles` INT NOT NULL,
  `Username` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC),
  INDEX `fk_Users_Permissions1_idx` (`idRoles` ASC),
  CONSTRAINT `fk_Users_Permissions1`
    FOREIGN KEY (`idRoles`)
    REFERENCES `quizshow_millionaire`.`Permissions` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`Lifeline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`Lifeline` (
  `idLifeline` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Status` TINYINT(1) NULL,
  PRIMARY KEY (`idLifeline`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`Lifelines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`Lifelines` (
  `idLifelines` INT NOT NULL,
  `idLifeline` INT NOT NULL,
  PRIMARY KEY (`idLifelines`),
  INDEX `fk_Lifelines_Lifeline1_idx` (`idLifeline` ASC),
  CONSTRAINT `fk_Lifelines_Lifeline1`
    FOREIGN KEY (`idLifeline`)
    REFERENCES `quizshow_millionaire`.`Lifeline` (`idLifeline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`PlayerState`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`PlayerState` (
  `idPlayerState` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlayerState`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`Players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`Players` (
  `idPlayers` INT NOT NULL AUTO_INCREMENT,
  `idUsers` INT NOT NULL,
  `idLifelines` INT NOT NULL,
  `idPlayerState` INT NOT NULL,
  `Nickname` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlayers`),
  UNIQUE INDEX `idPlayers_UNIQUE` (`idPlayers` ASC),
  INDEX `fk_Players_Users1_idx` (`idUsers` ASC),
  INDEX `fk_Players_Lifelines1_idx` (`idLifelines` ASC),
  INDEX `fk_Players_PlayerState1_idx` (`idPlayerState` ASC),
  CONSTRAINT `fk_Players_Users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `quizshow_millionaire`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Players_Lifelines1`
    FOREIGN KEY (`idLifelines`)
    REFERENCES `quizshow_millionaire`.`Lifelines` (`idLifelines`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Players_PlayerState1`
    FOREIGN KEY (`idPlayerState`)
    REFERENCES `quizshow_millionaire`.`PlayerState` (`idPlayerState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`Hosts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`Hosts` (
  `idHosts` INT NOT NULL AUTO_INCREMENT,
  `idUsers` INT NOT NULL,
  `GamesHosted` INT NULL,
  PRIMARY KEY (`idHosts`),
  INDEX `fk_Hosts_Users1_idx` (`idUsers` ASC),
  UNIQUE INDEX `idHosts_UNIQUE` (`idHosts` ASC),
  CONSTRAINT `fk_Hosts_Users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `quizshow_millionaire`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`Questions` (
  `idQuestions` INT NOT NULL AUTO_INCREMENT,
  `Text` VARCHAR(100) NOT NULL,
  `Difficulty` INT NOT NULL,
  PRIMARY KEY (`idQuestions`),
  UNIQUE INDEX `idQuestions_UNIQUE` (`idQuestions` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`QuestionsSets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`QuestionsSets` (
  `idQuestionsSets` INT NOT NULL AUTO_INCREMENT,
  `idQuestions` INT NOT NULL,
  PRIMARY KEY (`idQuestionsSets`),
  UNIQUE INDEX `idQuestionsSets_UNIQUE` (`idQuestionsSets` ASC),
  INDEX `fk_QuestionsSets_Questions1_idx` (`idQuestions` ASC),
  CONSTRAINT `fk_QuestionsSets_Questions1`
    FOREIGN KEY (`idQuestions`)
    REFERENCES `quizshow_millionaire`.`Questions` (`idQuestions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`SessionsState`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`SessionsState` (
  `idSessionsState` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idSessionsState`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`Sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`Sessions` (
  `idSession` INT NOT NULL AUTO_INCREMENT,
  `idQuestionsSets` INT NOT NULL,
  `idHost` INT NOT NULL,
  `idPlayers` INT NOT NULL,
  `idSessionsState` INT NOT NULL,
  PRIMARY KEY (`idSession`),
  UNIQUE INDEX `idGamesHosted_UNIQUE` (`idSession` ASC),
  INDEX `fk_Sessions_QuestionsSets1_idx` (`idQuestionsSets` ASC),
  INDEX `fk_Sessions_Hosts1_idx` (`idHost` ASC),
  INDEX `fk_Sessions_Players1_idx` (`idPlayers` ASC),
  INDEX `fk_Sessions_SessionsState1_idx` (`idSessionsState` ASC),
  CONSTRAINT `fk_Sessions_QuestionsSets1`
    FOREIGN KEY (`idQuestionsSets`)
    REFERENCES `quizshow_millionaire`.`QuestionsSets` (`idQuestionsSets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sessions_Hosts1`
    FOREIGN KEY (`idHost`)
    REFERENCES `quizshow_millionaire`.`Hosts` (`idHosts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sessions_Players1`
    FOREIGN KEY (`idPlayers`)
    REFERENCES `quizshow_millionaire`.`Players` (`idPlayers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sessions_SessionsState1`
    FOREIGN KEY (`idSessionsState`)
    REFERENCES `quizshow_millionaire`.`SessionsState` (`idSessionsState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`Answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`Answers` (
  `idAnswers` INT NOT NULL,
  `idQuestion` INT NOT NULL,
  `Text` VARCHAR(100) NULL,
  `Correct` TINYINT(1) NULL,
  PRIMARY KEY (`idAnswers`),
  INDEX `fk_Answers_Questions1_idx` (`idQuestion` ASC),
  CONSTRAINT `fk_Answers_Questions1`
    FOREIGN KEY (`idQuestion`)
    REFERENCES `quizshow_millionaire`.`Questions` (`idQuestions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`QuestionStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`QuestionStats` (
  `idQuestionStats` INT NOT NULL AUTO_INCREMENT,
  `idQuestions` INT NOT NULL,
  `CorrectlyAnswered` INT NULL,
  `IncorrectlyAnswered` INT NULL,
  `LifelineUsed` INT NULL,
  INDEX `fk_QuestionStats_Questions1_idx` (`idQuestions` ASC),
  PRIMARY KEY (`idQuestionStats`),
  UNIQUE INDEX `idQuestionStats_UNIQUE` (`idQuestionStats` ASC),
  CONSTRAINT `fk_QuestionStats_Questions1`
    FOREIGN KEY (`idQuestions`)
    REFERENCES `quizshow_millionaire`.`Questions` (`idQuestions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizshow_millionaire`.`UserStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizshow_millionaire`.`UserStats` (
  `idPlayerStats` INT NOT NULL,
  `idUsers` INT NOT NULL,
  `TotalEarning` INT NULL,
  `GamesPlayed` INT NULL,
  `GamesAbandoned` INT NULL,
  `GamesWon` INT NULL,
  PRIMARY KEY (`idPlayerStats`),
  INDEX `fk_UserStats_Users1_idx` (`idUsers` ASC),
  CONSTRAINT `fk_UserStats_Users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `quizshow_millionaire`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
